server {
    listen       8080;
    server_name  _;
    root   /usr/share/nginx/html;
    index  index.html;

    # Compresión para texto/HTML
    gzip on;
    gzip_types text/plain text/css application/javascript application/json image/svg+xml;
    gzip_min_length 256;

    location / {
        try_files $uri $uri/ /index.html;
    }

    # Cache largo solo para assets versionados; el HTML siempre fresco
    location = /index.html {
        add_header Cache-Control "no-cache";
    }
}
